"""Curated comprehensive translations for residue strings."""

CURATED_RESIDUE = {
    # Medium & Long Strings
    "05NPO+owb0": "已附加 {filename}。",
    "1NNiypJa+g": "包含 <u>任务过程记录</u>",
    "1U2EAlioCu": "使用 Anthropic 推荐的默认设置",
    "2wZFVb6pD6": "已处理的体验",
    "3p+PBJPMTa": "辅助程序刷新缓冲区 (秒)",
    "4IYrcQGEZ0": "{action}：{audience}",
    "5pcUlQ/ECD": "{title} <cmd>/{command}</cmd> — {blurb}",
    "5xK0+uamyq": "自动充值说明",
    "6XeDArE1XW": "包含 /anthropic 路径的完整 SDK 基本 URL（替换 bedrock-mantle.REGION.api.aws/anthropic）。",
    "85wBNMO4C5": "按平台替换",
    "8ihxJRYpI4": "完成取消",
    "8uN+pRpuBV": "员工身份 IdP (OIDC)",
    "9jut5bkOz9": "Cron 表达式 (UTC)",
    "9mwumR+MwB": "包含 Claude 的提案",
    "B9l27BNEGU": "员工身份受众",
    "BIhNXWv4cN": "查看已解析的 curl 示例",
    "BZXZOt1S3p": "{period, select, daily {每日} weekly {每周} other {每月}}",
    "BoeLY1XcsX": "(<link>了解更多</link>。)",
    "C5t5Fbv4UY": "{count, number} / {limit, number}",
    "CiPQBkMZ6H": "{filename} · 生效日期：{date}",
    "CmuPw/Tgxw": "{category}：{actions}",
    "DGbvpNk68R": "包含 Claude Design，以及：",
    "DsrWLt4HJD": "无法完成分析查询。",
    "F/XfP2ZLIg": "开发者合作伙伴计划",
    "F0aXEjuelO": "{filename} · 涵盖 {juris} · 过期日期：{date}",
    "FH9mIrYIr6": "{attempts, plural, one {# 次尝试} other {# 次尝试}}。",
    "FtuI0DrmqS": "重新启动 Claude Desktop",
    "G6h1m5lQe0": "银行卡验证失败",
    "GCiKUALiJT": "阶段：{title}，{status}",
    "Gi7sf5ObGK": "正在使用 {connectorName}…",
    "GipYo/bPxn": "有趣的产品设计发布",
    "HhOWSUTxff": "Vertex OAuth 登录提示",
    "HyH44Jl2y/": "Claude 按下了 Apple Pay",
    "I1dq7LLXYm": "正在筛选记忆",
    "IOYwx8J2DP": "{filename} · 已于 {date} 过期",
    "IS2pe5BXXq": "通用 URL (推荐)",
    "IpLDZD1WYL": "现有访问权限不受影响。",
    "JMclbUOpS1": "{filename}，{lineCount, plural, one {# 行} other {# 行}}",
    "JXlAcBeGVh": "{approx, select, yes {约 } other {}}{schedule}",
    "JjELcR65sL": "可用性信息",
    "Jzewj48WEu": "正在阅读 <b>{title}</b>",
    "LGqEp7vUY8": "守护进程脚本执行失败",
    "LWMFZWUAJi": "正在分析 {filename}…",
    "Log2FwVcHz]": "研究 · 12 个来源",
    "Log2FwVcHz": "研究 · 12 个来源",
    "Ls4pTMF2tQ": "{wall} 实际时间 · {api} API",
    "MBNotx/VaO": "不喜欢引用的来源",
    "MFIP3X2G7h": "<name>{orgLabel}</name>：{changes}",
    "MT4YqaMZRp": "显示 {count, plural, one {# 个机密} other {# 个机密}}",
    "N/3DZILFD+": "让 Claude 跨应用程序工作",
    "NrSr3ZjYZt": "Stripe Webhook 机密",
    "OIJOcSxF7T": "自定义 → {section}",
    "OJwrDu7v0K": "完成设置向导",
    "PyFqSVoPMR": "作者身份验证",
    "QAhGitfpyD": "撰写明天的简报",
    "QB7neZ8lEn": "{announcement}。{extra}",
    "R1BROOAuq8": "今日 Slack 提及",
    "SDGVBWkOFy": "包含 Claude Science",
    "SaQMb1MDfJ": "请少用破折号",
    "TRCxE5a/GS": "已花费 {spend} · 无限制",
    "TVdWaZSDJo": "远程控制已关闭。",
    "U7gusYA1jb": "使用 {name} 时研究功能不可用",
    "U7pKnlXryO": "正在梳理记忆",
    "VbB5ek1XTP": "标头前缀 (可选)",
    "Vjsm3qiIh7": "<a>#{number}</a> 已修改 {modifiedLabel}",
    "Vs3jMi8puF": "身份验证方式",
    "WP38t4MZJs": "域名认领已发起。",
    "WWCTOc9uiI": "· {count, plural, one {# 条建议} other {# 条建议}}",
    "WarDMMQa6d": "不支持的架构",
    "Wr/QCLlnmw": "将所有内容合并为最终输出",
    "X0gScIe71+": "综合 41 次客户通话",
    "X3m8IsqFPF": "GitHub App 安装",
    "XVFBDtDWMz": "媒体与娱乐",
    "Xjucw5aYiY": "OAuth 发现替换",
    "YAgO/yJ+kJ": "第三方分析",
    "YW1TREYZK3": "未达到预期",
    "ZklznS3CYL": "通过 URL 强制执行 (?ef_force=)",
    "ZprxEsuIBU": "第三季度：1820 万美元，低 6%",
    "aZEuarDLlh": "追加 offline_access",
    "awiUcrPYT7": "工作树需要修复",
    "b8sKoQHACN": "（当前为 {modelName}）",
    "bRMBQMB4sx": "播放 Claude Design 演示视频",
    "ba7Q0xdFHr": "#{number} 已于 {modifiedAbsolute} 修改",
    "bbNPFA8I6S": "{filename} · 涵盖 {juris}",
    "cl129b/6Ns": "已起草演讲者备注 · 每张幻灯片均附有来源链接",
    "d91p7ilk+c": "（{defaultsByProduct}）",
    "d9W1+Nu6vO": "保留访问权限至 {date}",
    "dKEgofbwpe": "员工身份 (STS)",
    "dMfmUWYglY": "未使用 · 过期时间：{expiresAt}",
    "dplDsSbTtl": "部署显示副标题",
    "fYWmBpqW1S": "已取消发布“{name}”",
    "fzfvmE8SAV": "{brand} •••• {last4}",
    "g+OXwX4qeB": "{control}：{selection}",
    "g9F5pdRbzX": "总支出：{value}",
    "iQjN0k8bKD": "其他授权类型",
    "ihFcahKXi2": "包含 {productName}，以及：",
    "j65oVgNvJh": "Claude {planLabel} 访问权限立即终止",
    "jQ9aTNkSI3": "Claude 点击了“最近”",
    "kMJ7N+HH1m": "包含 Claude Design",
    "lOLpSf+qgW": "建议：{suggestion}",
    "m/Ss+fqfqN": "正在取消发布“{name}”…",
    "nSeeRT4sts": "{name}（不可用）",
    "oWCbrRNN5e": "· {count, plural, one {# 个资源} other {# 个资源}}",
    "qcxnX5qb+q": "Acme 续订报价周五到期",
    "s+7ETv7BJi": "{version} 已取消发布。",
    "wGU0z/x1BK": "{count, number} / {max, number} 个字符",
    "wPm6BlASlF": "没有匹配“{query}”的内容",
    "xNKI+ggLdK": "{period, select, daily {每日} weekly {每周} other {每月}}",
    "xc/XJysAe5": "预估 {amount} / 合并的 PR（30天）",
    "y21MM8aMFb": "条目 {n}：{message}",
    "yC36yqMB5z": "健康与生命科学",
    "yv2tywlD46": "{author} · {updated} 更新",
    "zAF5NIDRoE": "无法分析该证书。",
    "zMXMJ7nsTR": "正在浏览记忆",
    "ziKxNhHkWo]": "正在快进分支…",
    "ziKxNhHkWo": "正在快进分支…",

    # Short Strings
    "D2W6fLXiNK": "工作树",
    "E7BiLAdijs": "首席执行官 (CEO)",
    "E7LFF2+KCa": "敏捷专家 (Scrum Master)",
    "BjoCZjjj3K": "第 {rank} 名",
    "hBOiIdiP4U": "macOS (Apple Silicon)",
    "oNp1waFarV": "Latin-1 (ISO-8859-1)",
    "u6WcCZIyyg": "Research Labs Premium：{before, number} → {after, number}",
    "5RasbgfW2t": "Research Labs：{before, number} → {after, number}",
    "LN/zd9G8eM": "聊天 + Claude Code：{before, number} → {after, number}",
    "hiC8I+PyBe": "Claude Enterprise：{before, number} → {after, number}",
    "0NqPGMfepJ": "显示前 {count, number} 个",
    "0z036KPr8s": "移除 {count, number} 个",
    "CiInu5rHMt": "查看全部 {count, number} 个插件",
    "GMqJDupFXJ": "查看全部 {count, number} 个连接器",
}
