"""Translation dictionary and rules for Claude Desktop Chinese."""

# 1. Exact phrase mapping table for common UI strings, buttons, menus, dialogs
EXACT_PHRASES = {
    "Save": "保存",
    "Cancel": "取消",
    "Confirm": "确认",
    "Delete": "删除",
    "Remove": "移除",
    "Edit": "编辑",
    "Update": "更新",
    "Add": "添加",
    "Create": "创建",
    "Close": "关闭",
    "Done": "完成",
    "Back": "返回",
    "Next": "下一步",
    "Continue": "继续",
    "Retry": "重试",
    "Open": "打开",
    "View": "查看",
    "Search": "搜索",
    "Filter": "筛选",
    "Sort": "排序",
    "Settings": "设置",
    "General": "通用",
    "Account": "账户",
    "Profile": "个人资料",
    "Security": "安全",
    "Privacy": "隐私",
    "Billing": "账单",
    "Subscription": "订阅",
    "Plans": "计划",
    "Usage": "使用量",
    "Limits": "限额",
    "Spend limits": "支出限额",
    "Usage credits": "使用额度",
    "Credits": "额度",
    "Members": "成员",
    "Groups": "群组",
    "Roles": "角色",
    "Permissions": "权限",
    "Projects": "项目",
    "Artifacts": "制品",
    "Artifact": "制品",
    "Connectors": "连接器",
    "Connector": "连接器",
    "Plugins": "插件",
    "Plugin": "插件",
    "Marketplace": "市场",
    "Directory": "目录",
    "Skills": "技能",
    "Skill": "技能",
    "Tools": "工具",
    "Tool": "工具",
    "MCP": "MCP",
    "MCP Server": "MCP 服务器",
    "MCP Servers": "MCP 服务器",
    "MCP Tool": "MCP 工具",
    "MCP Tools": "MCP 工具",
    "Computer Use": "计算机使用",
    "Context Window": "上下文窗口",
    "Extended Thinking": "扩展思考",
    "Thinking Mode": "思考模式",
    "Thinking": "思考中",
    "Thinking process": "思考过程",
    "Thinking transcript": "思考过程记录",
    "Custom Instructions": "自定义指令",
    "Prompt Caching": "提示词缓存",
    "Claude Code": "Claude Code",
    "Cowork": "协同 (Cowork)",
    "Routine": "例程",
    "Routines": "例程",
    "Sessions": "会话",
    "Session": "会话",
    "Chats": "聊天",
    "Chat": "聊天",
    "Conversations": "对话",
    "Conversation": "对话",
    "Messages": "消息",
    "Message": "消息",
    "Files": "文件",
    "File": "文件",
    "Folders": "文件夹",
    "Folder": "文件夹",
    "Repositories": "代码仓库",
    "Repository": "代码仓库",
    "Repo": "代码仓库",
    "Code": "代码",
    "Terminal": "终端",
    "Shell": "Shell",
    "Runner": "运行器",
    "Runners": "运行器",
    "Workspace": "工作区",
    "Workspaces": "工作区",
    "Organization": "组织",
    "Organizations": "组织",
    "Org": "组织",
    "Admin": "管理员",
    "Admins": "管理员",
    "Owner": "所有者",
    "Owners": "所有者",
    "Primary Owner": "主所有者",
    "User": "用户",
    "Users": "用户",
    "Guest": "访客",
    "Guests": "访客",
    "Member": "成员",
    "Learn more": "了解更多",
    "Learn More": "了解更多",
    "Read more": "阅读更多",
    "See all": "查看全部",
    "Show all": "显示全部",
    "View all": "查看全部",
    "See details": "查看详情",
    "View details": "查看详情",
    "Show more": "显示更多",
    "Show less": "显示更少",
    "Collapse": "折叠",
    "Expand": "展开",
    "Copy": "复制",
    "Copied": "已复制",
    "Cut": "剪切",
    "Paste": "粘贴",
    "Select all": "全选",
    "Deselect all": "取消全选",
    "Clear": "清除",
    "Clear all": "清除全部",
    "Reset": "重置",
    "Restore": "恢复",
    "Backup": "备份",
    "Download": "下载",
    "Upload": "上传",
    "Import": "导入",
    "Export": "导出",
    "Share": "分享",
    "Shared": "已分享",
    "Publish": "发布",
    "Published": "已发布",
    "Archive": "归档",
    "Archived": "已归档",
    "Unarchive": "取消归档",
    "Disable": "禁用",
    "Disabled": "已禁用",
    "Enable": "启用",
    "Enabled": "已启用",
    "Turn on": "开启",
    "Turn off": "关闭",
    "Switch": "切换",
    "Upgrade": "升级",
    "Downgrade": "降级",
    "Manage": "管理",
    "Configure": "配置",
    "Install": "安装",
    "Installed": "已安装",
    "Uninstall": "卸载",
    "Uninstalled": "已卸载",
    "Reinstall": "重新安装",
    "Connect": "连接",
    "Connected": "已连接",
    "Disconnect": "断开连接",
    "Disconnected": "已断开连接",
    "Reconnect": "重新连接",
    "Reconnecting": "正在重新连接",
    "Connecting": "正在连接",
    "Loading": "正在加载",
    "Loading...": "正在加载...",
    "Saving": "正在保存",
    "Saving...": "正在保存...",
    "Deleting": "正在删除",
    "Deleting...": "正在删除...",
    "Updating": "正在更新",
    "Updating...": "正在更新...",
    "Processing": "正在处理",
    "Processing...": "正在处理...",
    "Searching": "正在搜索",
    "Searching...": "正在搜索...",
    "Scanning": "正在扫描",
    "Scanning...": "正在扫描...",
    "Success": "成功",
    "Successful": "成功",
    "Error": "错误",
    "Warning": "警告",
    "Info": "信息",
    "Notice": "提示",
    "Help": "帮助",
    "Support": "支持",
    "Documentation": "文档",
    "Docs": "文档",
    "Feedback": "反馈",
    "Report an issue": "报告问题",
    "Contact support": "联系支持",
    "About": "关于",
    "Version": "版本",
    "What’s new": "最新功能",
    "Release notes": "发行说明",
    "Sign in": "登录",
    "Sign out": "退出登录",
    "Log in": "登录",
    "Log out": "退出登录",
    "Sign up": "注册",
    "Register": "注册",
    "Get started": "开始使用",
    "Try again": "重试",
    "Try now": "立即尝试",
    "Upgrade now": "立即升级",
    "Join": "加入",
    "Leave": "离开",
    "Invite": "邀请",
    "Invite members": "邀请成员",
    "Pending invites": "待处理邀请",
    "Revoke": "撤销",
    "Revoked": "已撤销",
    "Approve": "批准",
    "Approved": "已批准",
    "Reject": "拒绝",
    "Rejected": "已拒绝",
    "Allow": "允许",
    "Allowed": "已允许",
    "Block": "阻止",
    "Blocked": "已阻止",
    "Deny": "拒绝",
    "Denied": "已拒绝",
    "Always allow": "始终允许",
    "Ask every time": "每次询问",
    "Ask each time": "每次询问",
    "Never allow": "从不允许",
    "Optional": "可选",
    "Required": "必填",
    "Default": "默认",
    "Custom": "自定义",
    "Active": "活跃",
    "Inactive": "未激活",
    "Pending": "等待中",
    "Draft": "草稿",
    "Public": "公开",
    "Private": "私密",
    "Internal": "内部",
    "External": "外部",
    "All": "全部",
    "None": "无",
    "Other": "其他",
    "Unknown": "未知",
    "Beta": "Beta 测试版",
    "Alpha": "Alpha 测试版",
    "Preview": "预览",
    "Experimental": "实验性",
}
