"""Full-scale Translation Engine & Terminology Harmonizer for Claude Desktop Chinese."""

import json
import re
import sys
from pathlib import Path
from typing import Dict, Tuple, List, Optional, Any

from glossary import harmonize_text
from masking import mask_text, unmask_text
from direct_translations import DIRECT_TRANSLATIONS, TECHNICAL_PRESERVE
from phrase_dict import EXACT_PHRASES

ROOT = Path(__file__).resolve().parents[2]
UNTRANSLATED_FILE = ROOT / ".agents" / "worker_m2_r2" / "untranslated.json"

with open(UNTRANSLATED_FILE, "r", encoding="utf-8") as f:
    untranslated = json.load(f)

print(f"Loaded {len(untranslated)} untranslated items.")

# Comprehensive Verb Table
VERBS = {
    "add": "添加", "adds": "添加", "added": "已添加", "adding": "正在添加",
    "create": "创建", "creates": "创建", "created": "已创建", "creating": "正在创建",
    "delete": "删除", "deletes": "删除", "deleted": "已删除", "deleting": "正在删除",
    "remove": "移除", "removes": "移除", "removed": "已移除", "removing": "正在移除",
    "edit": "编辑", "edits": "编辑", "edited": "已编辑", "editing": "正在编辑",
    "update": "更新", "updates": "更新", "updated": "已更新", "updating": "正在更新",
    "save": "保存", "saves": "保存", "saved": "已保存", "saving": "正在保存",
    "cancel": "取消", "cancels": "取消", "canceled": "已取消", "cancelling": "正在取消",
    "confirm": "确认", "confirms": "确认", "confirmed": "已确认", "confirming": "正在确认",
    "retry": "重试", "retries": "重试", "retried": "已重试", "retrying": "正在重试",
    "continue": "继续", "continues": "继续", "continued": "已继续", "continuing": "正在继续",
    "close": "关闭", "closes": "关闭", "closed": "已关闭", "closing": "正在关闭",
    "open": "打开", "opens": "打开", "opened": "已打开", "opening": "正在打开",
    "view": "查看", "views": "查看", "viewed": "已查看", "viewing": "正在查看",
    "search": "搜索", "searches": "搜索", "searched": "已搜索", "searching": "正在搜索",
    "select": "选择", "selects": "选择", "selected": "已选择", "selecting": "正在选择",
    "choose": "选择", "chooses": "选择", "chosen": "已选择", "choosing": "正在选择",
    "download": "下载", "downloads": "下载", "downloaded": "已下载", "downloading": "正在下载",
    "upload": "上传", "uploads": "上传", "uploaded": "已上传", "uploading": "正在上传",
    "import": "导入", "imports": "导入", "imported": "已导入", "importing": "正在导入",
    "export": "导出", "exports": "导出", "exported": "已导出", "exporting": "正在导出",
    "share": "分享", "shares": "分享", "shared": "已分享", "sharing": "正在分享",
    "publish": "发布", "publishes": "发布", "published": "已发布", "publishing": "正在发布",
    "archive": "归档", "archives": "归档", "archived": "已归档", "archiving": "正在归档",
    "enable": "启用", "enables": "启用", "enabled": "已启用", "enabling": "正在启用",
    "disable": "禁用", "disables": "禁用", "disabled": "已禁用", "disabling": "正在禁用",
    "manage": "管理", "manages": "管理", "managed": "已管理", "managing": "正在管理",
    "configure": "配置", "configures": "配置", "configured": "已配置", "configuring": "正在配置",
    "install": "安装", "installs": "安装", "installed": "已安装", "installing": "正在安装",
    "uninstall": "卸载", "uninstalls": "卸载", "uninstalled": "已卸载", "uninstalling": "正在卸载",
    "connect": "连接", "connects": "连接", "connected": "已连接", "connecting": "正在连接",
    "disconnect": "断开连接", "disconnects": "断开连接", "disconnected": "已断开连接",
    "reconnect": "重新连接", "reconnects": "重新连接", "reconnected": "已重新连接", "reconnecting": "正在重新连接",
    "invite": "邀请", "invites": "邀请", "invited": "已邀请", "inviting": "正在邀请",
    "revoke": "撤销", "revokes": "撤销", "revoked": "已撤销", "revoking": "正在撤销",
    "approve": "批准", "approves": "批准", "approved": "已批准", "approving": "正在批准",
    "reject": "拒绝", "rejects": "拒绝", "rejected": "已拒绝", "rejecting": "正在拒绝",
    "allow": "允许", "allows": "允许", "allowed": "已允许", "allowing": "正在允许",
    "block": "阻止", "blocks": "阻止", "blocked": "已阻止", "blocking": "正在阻止",
    "deny": "拒绝", "denies": "拒绝", "denied": "已拒绝", "denying": "正在拒绝",
    "verify": "验证", "verifies": "验证", "verified": "已验证", "verifying": "正在验证",
    "load": "加载", "loads": "加载", "loaded": "已加载", "loading": "正在加载",
    "send": "发送", "sends": "发送", "sent": "已发送", "sending": "正在发送",
    "receive": "接收", "receives": "接收", "received": "已接收", "receiving": "正在接收",
    "start": "开始", "starts": "开始", "started": "已开始", "starting": "正在开始",
    "stop": "停止", "stops": "停止", "stopped": "已停止", "stopping": "正在停止",
    "pause": "暂停", "pauses": "暂停", "paused": "已暂停", "pausing": "正在暂停",
    "resume": "恢复", "resumes": "恢复", "resumed": "已恢复", "resuming": "正在恢复",
    "restart": "重启", "restarts": "重启", "restarted": "已重启", "restarting": "正在重启",
    "reset": "重置", "resets": "重置", "resetting": "正在重置",
    "restore": "恢复", "restores": "恢复", "restored": "已恢复", "restoring": "正在恢复",
    "copy": "复制", "copies": "复制", "copied": "已复制", "copying": "正在复制",
    "paste": "粘贴", "pastes": "粘贴", "pasted": "已粘贴", "pasting": "正在粘贴",
    "check": "检查", "checks": "检查", "checked": "已检查", "checking": "正在检查",
    "scan": "扫描", "scans": "扫描", "scanned": "已扫描", "scanning": "正在扫描",
    "sync": "同步", "syncs": "同步", "synced": "已同步", "syncing": "正在同步",
    "run": "运行", "runs": "运行", "running": "正在运行", "ran": "已运行",
    "set": "设置", "sets": "设置", "setting": "正在设置",
    "get": "获取", "gets": "获取", "got": "已获取", "getting": "正在获取",
    "show": "显示", "shows": "显示", "showed": "已显示", "shown": "已显示", "showing": "正在显示",
    "hide": "隐藏", "hides": "隐藏", "hidden": "已隐藏", "hiding": "正在隐藏",
    "apply": "应用", "applies": "应用", "applied": "已应用", "applying": "正在应用",
    "clear": "清除", "clears": "清除", "cleared": "已清除", "clearing": "正在清除",
    "dismiss": "关闭", "dismisses": "关闭", "dismissed": "已关闭", "dismissing": "正在关闭",
    "help": "帮助", "helps": "帮助", "helped": "已帮助", "helping": "正在帮助",
    "explain": "解释", "explains": "解释", "explained": "已解释", "explaining": "正在解释",
    "summarize": "总结", "summarizes": "总结", "summarized": "已总结", "summarizing": "正在总结",
    "review": "审查", "reviews": "审查", "reviewed": "已审查", "reviewing": "正在审查",
    "generate": "生成", "generates": "生成", "generated": "已生成", "generating": "正在生成",
    "find": "查找", "finds": "查找", "found": "已找到", "finding": "正在查找",
    "fix": "修复", "fixes": "修复", "fixed": "已修复", "fixing": "正在修复",
    "upgrade": "升级", "upgrades": "升级", "upgraded": "已升级", "upgrading": "正在升级",
    "downgrade": "降级", "downgrades": "降级", "downgraded": "已降级", "downgrading": "正在降级",
    "switch": "切换", "switches": "切换", "switched": "已切换", "switching": "正在切换",
    "turn on": "开启", "turns on": "开启", "turned on": "已开启", "turning on": "正在开启",
    "turn off": "关闭", "turns off": "关闭", "turned off": "已关闭", "turning off": "正在关闭",
}

# Comprehensive Noun & Entity Table
NOUNS = {
    "settings": "设置", "setting": "设置",
    "account": "账户", "accounts": "账户",
    "profile": "个人资料", "profiles": "个人资料",
    "security": "安全", "privacy": "隐私",
    "billing": "账单", "subscription": "订阅", "subscriptions": "订阅",
    "plan": "计划", "plans": "计划",
    "usage": "使用量",
    "limit": "限额", "limits": "限额",
    "spend limit": "支出限额", "spend limits": "支出限额",
    "usage credit": "使用额度", "usage credits": "使用额度",
    "credit": "额度", "credits": "额度",
    "member": "成员", "members": "成员",
    "group": "群组", "groups": "群组",
    "role": "角色", "roles": "角色",
    "custom role": "自定义角色", "custom roles": "自定义角色",
    "permission": "权限", "permissions": "权限",
    "project": "项目", "projects": "项目",
    "artifact": "制品", "artifacts": "制品",
    "connector": "连接器", "connectors": "连接器",
    "plugin": "插件", "plugins": "插件",
    "marketplace": "市场", "directory": "目录",
    "skill": "技能", "skills": "技能",
    "tool": "工具", "tools": "工具",
    "session": "会话", "sessions": "会话",
    "chat": "聊天", "chats": "聊天",
    "conversation": "对话", "conversations": "对话",
    "message": "消息", "messages": "消息",
    "file": "文件", "files": "文件",
    "folder": "文件夹", "folders": "文件夹",
    "directory": "目录", "directories": "目录",
    "repository": "代码仓库", "repositories": "代码仓库",
    "repo": "代码仓库", "repos": "代码仓库",
    "code": "代码", "terminal": "终端", "shell": "Shell",
    "runner": "运行器", "runners": "运行器",
    "workspace": "工作区", "workspaces": "工作区",
    "organization": "组织", "organizations": "组织",
    "admin": "管理员", "admins": "管理员",
    "owner": "所有者", "owners": "所有者",
    "user": "用户", "users": "用户",
    "guest": "访客", "guests": "访客",
    "seat": "席位", "seats": "席位",
    "routine": "例程", "routines": "例程",
    "prompt": "提示词", "prompts": "提示词",
    "model": "模型", "models": "模型",
    "environment": "环境", "environments": "环境",
    "task": "任务", "tasks": "任务",
    "status": "状态", "detail": "详情", "details": "详情",
    "error": "错误", "errors": "错误",
    "warning": "警告", "warnings": "警告",
    "info": "信息", "notice": "提示",
    "help": "帮助", "support": "支持", "docs": "文档",
    "feedback": "反馈", "version": "版本",
    "name": "名称", "names": "名称",
    "description": "描述", "descriptions": "描述",
    "title": "标题", "titles": "标题",
    "date": "日期", "dates": "日期",
    "time": "时间", "times": "时间",
    "month": "月份", "months": "月份",
    "year": "年份", "years": "年份",
    "day": "天", "days": "天",
    "hour": "小时", "hours": "小时",
    "minute": "分钟", "minutes": "分钟",
    "second": "秒", "seconds": "秒",
    "week": "周", "weeks": "周",
    "weekday": "工作日", "weekdays": "工作日",
    "email": "邮箱", "emails": "邮箱",
    "password": "密码", "passwords": "密码",
    "token": "令牌", "tokens": "令牌",
    "api key": "API 密钥", "api keys": "API 密钥",
    "channel": "频道", "channels": "频道",
    "integration": "集成", "integrations": "集成",
    "summary": "摘要", "overview": "概览",
    "history": "历史记录", "log": "日志", "logs": "日志",
    "workflow": "工作流", "workflows": "工作流",
    "webhook": "Webhook", "webhooks": "Webhook",
    "request": "请求", "requests": "请求",
    "response": "响应", "responses": "响应",
    "device": "设备", "devices": "设备",
    "host": "主机", "hosts": "主机",
    "server": "服务器", "servers": "服务器",
    "client": "客户端", "clients": "客户端",
    "browser": "浏览器", "browsers": "浏览器",
    "network": "网络", "connection": "连接", "connections": "连接",
    "data": "数据", "content": "内容", "item": "项目", "items": "项目",
    "result": "结果", "results": "结果", "page": "页面", "pages": "页面",
    "window": "窗口", "windows": "窗口", "tab": "标签页", "tabs": "标签页",
    "button": "按钮", "buttons": "按钮", "icon": "图标", "icons": "图标",
    "menu": "菜单", "menus": "菜单", "dialog": "对话框", "dialogs": "对话框",
    "option": "选项", "options": "选项", "choice": "选择", "choices": "选择",
    "list": "列表", "lists": "列表", "table": "表格", "tables": "表格",
    "link": "链接", "links": "链接", "url": "URL", "urls": "URL",
    "change": "更改", "changes": "更改", "diff": "差异", "diffs": "差异",
    "patch": "补丁", "patches": "补丁", "fix": "修复", "fixes": "修复",
    "issue": "问题", "issues": "问题", "bug": "故障", "bugs": "故障",
    "feature": "功能", "features": "功能", "capability": "功能", "capabilities": "功能",
    "package": "包", "packages": "包", "bundle": "包", "bundles": "包",
    "container": "容器", "containers": "容器", "volume": "卷", "volumes": "卷",
    "image": "图片", "images": "图片", "document": "文档", "documents": "文档",
    "text": "文本", "string": "字符串", "number": "数字", "value": "值",
    "key": "密钥", "keys": "密钥", "field": "字段", "fields": "字段",
    "team": "团队", "teams": "团队", "company": "公司", "enterprise": "企业",
    "invoice": "发票", "invoices": "发票", "receipt": "收据", "receipts": "收据",
    "payment": "付款", "payments": "付款", "cost": "成本", "costs": "成本",
    "price": "价格", "prices": "价格", "fee": "费用", "fees": "费用",
    "rate": "费率", "rates": "费率", "amount": "金额", "amounts": "金额",
    "balance": "余额", "balances": "余额", "refund": "退款", "refunds": "退款",
    "tier": "层级", "tiers": "层级", "quota": "配额", "quotas": "配额",
    "threshold": "阈值", "thresholds": "阈值", "metric": "指标", "metrics": "指标",
    "event": "事件", "events": "事件", "hook": "钩子", "hooks": "钩子",
    "trigger": "触发器", "triggers": "触发器", "action": "操作", "actions": "操作",
    "instruction": "指令", "instructions": "指令", "step": "步骤", "steps": "步骤",
    "guide": "指南", "guides": "指南", "policy": "政策", "policies": "政策",
    "term": "条款", "terms": "条款", "rule": "规则", "rules": "规则",
    "license": "许可", "licenses": "许可", "agreement": "协议", "agreements": "协议",
}

print(f"Loaded {len(VERBS)} verbs and {len(NOUNS)} nouns.")
