"""Comprehensive translation engine for Claude Desktop Chinese localization."""

import json
import re
import sys
from pathlib import Path

# Common UI Phrase Dictionary (English -> Simplified Chinese)
PHRASE_DICT = {
    # Actions & Buttons
    "try again": "重试",
    "please try again": "请重试",
    "you can try again": "您可以重试",
    "learn more": "了解更多",
    "see details": "查看详情",
    "view details": "查看详情",
    "sign in": "登录",
    "sign out": "登出",
    "log in": "登录",
    "log out": "登出",
    "get started": "开始使用",
    "turn on": "开启",
    "turn off": "关闭",
    "switch to": "切换至",
    "save changes": "保存更改",
    "discard changes": "放弃更改",
    "clear all": "全部清除",
    "select all": "全选",
    "read aloud": "朗读",
    "stop reading": "停止朗读",
    "check for updates": "检查更新",
    "restart now": "立即重启",
    "restart claude": "重启 Claude",
    "continue in chat": "在对话中继续",
    "start a new chat": "开始新对话",
    "add to project": "添加到项目",
    "remove from project": "从项目中移除",
    "copy link": "复制链接",
    "share link": "分享链接",
    "download file": "下载文件",
    "upload file": "上传文件",
    "attach file": "附加文件",
    "drag and drop": "拖放",
    "open in browser": "在浏览器中打开",
    "open in finder": "在访达中打开",
    "open in explorer": "在资源管理器中打开",
    "open settings": "打开设置",
    "manage subscription": "管理订阅",
    "upgrade plan": "升级方案",
    "contact support": "联系支持",
    "back to chat": "返回对话",
    
    # Statuses & Notifications
    "in progress": "正在进行中",
    "completed": "已完成",
    "failed": "失败",
    "pending": "待处理",
    "canceled": "已取消",
    "paused": "已暂停",
    "running": "正在运行",
    "idle": "空闲",
    "ready": "就绪",
    "connecting": "正在连接",
    "connected": "已连接",
    "disconnected": "已断开连接",
    "enabled": "已启用",
    "disabled": "已禁用",
    "active": "活跃",
    "inactive": "非活跃",
    "available": "可用",
    "unavailable": "不可用",
    "up to date": "已是最新版本",
    
    # Features & Concepts
    "claude desktop": "Claude 桌面应用",
    "claude code": "Claude Code",
    "claude in chrome": "Chrome 中的 Claude",
    "cowork session": "Cowork 会话",
    "mcp server": "MCP 服务器",
    "mcp servers": "MCP 服务器",
    "mcp tool": "MCP 工具",
    "mcp tools": "MCP 工具",
    "mcp directory": "MCP 目录",
    "mcp client": "MCP 客户端",
    "computer use": "计算机使用",
    "artifacts": "制品",
    "artifact": "制品",
    "context window": "上下文窗口",
    "extended thinking": "扩展思考",
    "thinking mode": "深度思考",
    "prompt caching": "提示词缓存",
    "custom instructions": "自定义指令",
    "knowledge base": "知识库",
    "connectors": "连接器",
    "connector": "连接器",
    "system prompt": "系统提示词",
    "project knowledge": "项目知识库",
    "project files": "项目文件",
    "shared chats": "共享对话",
    "message limit": "消息限额",
    "usage limit": "用量限额",
    "spend limit": "消费限额",
    "daily limit": "每日限额",
    "monthly limit": "每月限额",
    "seat limit": "席位限额",
    "api key": "API 密钥",
    "access token": "访问令牌",
    "refresh token": "刷新令牌",
    "auth token": "授权令牌",
    "oauth client id": "OAuth 客户端 ID",
    "client secret": "客户端密钥",
    "redirect uri": "重定向 URI",
}
