"""Comprehensive translation rules and dictionary for Claude Desktop Chinese localization."""

import re

# Comprehensive Exact Match Translation Dictionary
EXACT_TRANSLATIONS = {
    # 1. Single Words & Short Labels
    "Runner": "运行器",
    "Settings": "设置",
    "General": "通用",
    "Account": "账户",
    "Appearance": "外观",
    "Language": "语言",
    "Theme": "主题",
    "Light": "浅色",
    "Dark": "深色",
    "System": "跟随系统",
    "Audio": "音频",
    "Microphone": "麦克风",
    "Speaker": "扬声器",
    "Speech": "语音",
    "Read Aloud": "朗读",
    "Voice": "声音",
    "Shortcuts": "快捷键",
    "Keyboard": "键盘",
    "Updates": "更新",
    "About": "关于",
    "Help": "帮助",
    "Support": "支持",
    "Privacy": "隐私",
    "Security": "安全",
    "Terms": "条款",
    "Terms of Service": "服务条款",
    "Privacy Policy": "隐私政策",
    "Feedback": "反馈",
    "Documentation": "文档",
    "Release Notes": "版本说明",
    "Check for Updates": "检查更新",
    "Checking for updates…": "正在检查更新…",
    "Up to date": "已是最新版本",
    "Restart to Update": "重启以更新",
    "Download": "下载",
    "Downloading…": "正在下载…",
    "Install": "安装",
    "Installing…": "正在安装…",
    "Uninstall": "卸载",
    "Save": "保存",
    "Saving…": "正在保存…",
    "Saved": "已保存",
    "Cancel": "取消",
    "Close": "关闭",
    "Done": "完成",
    "Confirm": "确认",
    "Delete": "删除",
    "Deleting…": "正在删除…",
    "Deleted": "已删除",
    "Remove": "移除",
    "Removing…": "正在移除…",
    "Removed": "已移除",
    "Edit": "编辑",
    "Editing…": "正在编辑…",
    "Create": "创建",
    "Creating…": "正在创建…",
    "Created": "已创建",
    "Add": "添加",
    "Adding…": "正在添加…",
    "Added": "已添加",
    "New": "新建",
    "New Chat": "新建对话",
    "New Project": "新建项目",
    "New Session": "新建会话",
    "Share": "分享",
    "Sharing…": "正在分享…",
    "Shared": "已分享",
    "Copy": "复制",
    "Copied": "已复制",
    "Paste": "粘贴",
    "Cut": "剪切",
    "Select All": "全选",
    "Clear": "清空",
    "Clear History": "清空历史记录",
    "Retry": "重试",
    "Refresh": "刷新",
    "Search": "搜索",
    "Filter": "筛选",
    "Sort": "排序",
    "Back": "返回",
    "Next": "下一步",
    "Previous": "上一步",
    "Continue": "继续",
    "Skip": "跳过",
    "Enable": "启用",
    "Enabled": "已启用",
    "Disable": "禁用",
    "Disabled": "已禁用",
    "Connect": "连接",
    "Connecting…": "正在连接…",
    "Connected": "已连接",
    "Disconnect": "断开连接",
    "Disconnected": "已断开连接",
    "Sign In": "登录",
    "Sign Out": "登出",
    "Log In": "登录",
    "Log Out": "登出",
    "Register": "注册",
    "Overview": "概览",
    "Details": "详情",
    "Status": "状态",
    "Active": "活跃",
    "Inactive": "非活跃",
    "Pending": "待处理",
    "Success": "成功",
    "Failed": "失败",
    "Error": "错误",
    "Warning": "警告",
    "Info": "信息",
    "Loading…": "正在加载…",
    "Please wait…": "请稍候…",
    
    # 2. Product Names & AI Features
    "Claude": "Claude",
    "Claude Desktop": "Claude 桌面应用",
    "Claude Desktop for macOS": "macOS 版 Claude 桌面应用",
    "Claude Desktop for Windows": "Windows 版 Claude 桌面应用",
    "Claude Code": "Claude Code",
    "Claude Code for Slack": "Slack 版 Claude Code",
    "Claude Security": "Claude 安全",
    "Anthropic API": "Anthropic API",
    "Model Context Protocol": "模型上下文协议 (MCP)",
    "MCP Server": "MCP 服务器",
    "MCP Servers": "MCP 服务器",
    "MCP Tools": "MCP 工具",
    "MCP Directory": "MCP 目录",
    "Computer Use": "计算机使用",
    "Artifacts": "制品",
    "Artifact": "制品",
    "Connectors": "连接器",
    "Connector": "连接器",
    "Context Window": "上下文窗口",
    "Extended Thinking": "扩展思考",
    "Thinking Mode": "深度思考",
    "Prompt Caching": "提示词缓存",
    "Projects": "项目",
    "Knowledge Base": "知识库",
    "Custom Instructions": "自定义指令",
    "Cowork": "Cowork",
    "Haiku": "Haiku",
    "Sonnet": "Sonnet",
    "Opus": "Opus",
    "Runner": "运行器",
    "Webhooks": "Webhooks",
    "Webhook": "Webhook",
}
